openapi: 3.0.0
info:
  title: Thorswap Composable Router API
  description: Swap between any assets to any other asset, 
  version: 0.0.3

servers:
  - url: http://api.thorswap-example.io/v1
    description: Main (production) server
  - url: http://staging-api.thorswap-example.io/v1
    description: Internal staging server for testing

paths:
  # INFO
  /health:
    get:
      summary: Returns current health of the server
      responses:
        '201':
          description: Ready
        '300':
          description: Not ready

  /providers:
    get:
      summary: List of available provider of liquidity sources
      responses:
        '200':
          description: A JSON array of providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
      
  /tokens:
    get:
      summary: List of tokens available for swap on Thorswap
      responses:
        '200':
          description: A JSON array of tokens
          content:
            application/json:
              schema:
                # Either this, or {[network]: [...tokens]}
                type: array
                items:
                  $ref: '#/components/schemas/Token'

  # SWAP
  /quote:
    get:
      summary: Returns a quote for the best aggregated swap between two assets, given input parameters
      parameters:
        - name: sellToken
          in: query
          required: true
          description: Token to sell
          schema:
            type: string
        - name: buyToken
          in: query
          required: true
          description: Token to buy
          schema:
            type: string
        - name: amount
          in: query
          required: true
          description: Amount of sellToken to sell
          schema:
            type: number
        # affiliateFeeBps
        - name: protocols
          in: query
          required: false
          description: Specify liquidity protocols to use (comma-separated). If not set, all liquidity protocols will be used
          schema:
            type: string
        - name: complexityLevel
          in: query
          required: false
          description: >
            Maximum number of hops to be used in a transaction.
            The more is used — the longer route estimation will take, the more complex route might be as a result.
            Default: 2
          schema:
            type: integer
      responses:
        '200':
          description: Best available quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '400':
          description: Insufficient liquidity, Cannot estimate, etc
  
    # /quotes:
    #   get:
    #     summary: Returns the best N quotes for a swap

  /swap:
    get:
      # Consideration:
      # Do we want to take 'quoteId' here, and require the user to generate a quote before initiating a swap?
      # If not, we need to include things like 'providers' in request to make sure the swap follows the same path as quoted 
      summary: Generates data for calling the Thorswap router
      parameters:
        - name: sellToken
          in: query
          required: true
          description: Token to sell
          schema:
            type: string
        - name: buyToken
          in: query
          required: true
          description: Token to buy
          schema:
            type: string
        - name: amount
          in: query
          required: true
          description: Amount of sellToken to sell
          schema:
            type: number
        - name: slippage
          in: query
          required: true
          description: Limit of price slippage you are willing to accept, as a percentage
          schema:
            type: number
        - name: protocols
          in: query
          required: false
          description: Specify liquidity protocols to use (comma-separated). If not set, all liquidity protocols will be used
          schema:
            type: string
        - name: complexityLevel
          in: query
          required: false
          description: >
            Maximum number of hops to be used in a transaction.
            The more is used — the longer route estimation will take, the more complex route might be as a result.
            Default: 2
          schema:
            type: integer
        - name: destAddress
          in: query
          required: false
          description: >
            Recipient address for the purchased token. If not set, fromAddress receives the output.
            If not set and output is on a different network, swap fails.
          schema:
            type: string
        - name: affiliateAddress
          in: query
          required: false
          description: Destination address for the affiliate fee output
          schema:
            type: string
        - name: affiliateFeeBps
          in: query
          required: false
          description: Fee that the affiliate receives for the swap, in basis-points (1bp=0.01%)
          schema:
            type: integer
      responses:
        '200':
          description: Data required to proceed with a swap from the frontend
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SwapData'

  # We'll want to keep track of ongoing swaps, so we can provide the user with status updates (e.g. Rango)
  # so something like /swap/initiate, /swap/{id}/status

  # We can also expose something like /swap/proceed, where we accept signed transactions and submit them to the relevant network on the user's behalf

components:
  schemas:
    Chain:
      type: object
      properties:
        id:
          description: Chain identifier # QUESTION: Is there a standard inclusive of both non-evm and evm blockchains?
          type: string
        name:
          description: Complete chain name 
          type: string
        gasToken:
          description: Token or coin used to pay for transaction fees on this blockchain
          $ref: '#/components/schemas/Token'
        evmId:
          description: If EVM chain, ID of chain (https://chainlist.org/)
          type: number
      required:
        - id
        - name

    # REVIEW: renamed this as it was the only model not matching the route url
    Provider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        supportedChains:
          type: array
          items:
            $ref: '#/components/schemas/Chain'
        logoURI:
          type: string
      required:
        - id
        - name
        - type
        - supportedChains

    Token:
      type: object
      properties:
        # Solo: Either 'ETH.XXX' symbols, or we use a separate 'network' property
        # Solo: Consideration: If 'ETH.XXX' format, then how do we express arbitrary contract addresses?
        # REVIEW: Oleg -> I really prefer adding a chain/network property
        symbol:
          description: The symbol representing the token
          type: string
        name:
          description: A human-friendly name for the token
          type: string
        address:
          description: The smart contract address of the token
          type: string
        chain:
          $ref: '#/components/schemas/Chain'
        decimals:
          description: The number of decimals needed to represent the token
          type: integer
        logoURL:
          description: A link to the token's logo
          type: string
      required:
        - symbol
        - name
        - address
        - chain
    
    Quote:
      type: object
      properties:
        sellToken:
          $ref: '#/components/schemas/Token'
        buyToken:
          $ref: '#/components/schemas/Token'
        sellAmount:
          type: number
        buyAmount:
          type: number
        route:
          type: array
          items:
            $ref: '#/components/schemas/Hop'
        estimatedFee:
          description: Estimated total fees for the swap # QUESTION: whats the reference unit or format here
          type: number
        estimatedSlippage:
          type: number
        # REVIEW: Human readable (2014-09-08T08:02:17.000Z) vs API ease of use (1360013296123).
        # REVIEW: For this project I prefer API ease of use -> epoch ms timestamp like 1360013296123 or moment().format('x') for good precision.
        timestamp:
          description: Timestamp that the quote was calculated (Unix Millisecond Timestamp)
          type: number
        # REVIEW: I think its more standard / easy to consume
        expiration:
          description: Expiration timestamp when the quote is considered stale or expired (Unix Millisecond Timestamp)
          type: number
        recommendedSlippage:
          description: Recommended slippage for the whole swap (e.g. 0.03 for 3%)
          type: number
    
    Hop:
      type: object
      properties:
        # REVIEW: I feel like it is best we reuse the Token component to inherit additional info
        sellToken:
          $ref: '#/components/schemas/Token'
        buyToken:
          $ref: '#/components/schemas/Token'
        sellAmount:
          description: 'How much token this hop aims to sell (e.g. "1.2" would refer to 1.2 units of the sellToken property)' # REVIEW: rephrase if not clear
          type: number
        buyAmount:
          description: 'How much token this hop aims to buy (e.g. "1.2" would refer to 1.2 units of the sellToken property)' # REVIEW: rephrase if not clear
          type: number
        provider:
          $ref: '#/components/schemas/Provider'
        estimatedFee:
          description: Estimated fee for the hop
          type: number
        description:
          description: Human-readable string describing the hop in detail
        transactionData:
          $ref: '#/components/schemas/TransactionData'
      required:
        - sellToken
        - buyToken
        - sellAmount
        - buyAmount
        - provider
    
    TransactionData:
      description: Data required to actually initiate the call from the frontend
      type: object
      # Shape will differ depending on the network
      # e.g. For Ethereum:
      # REVIEW: I think we would need the chain somewhere in there, maybe reuse the Token component but I'm not 100% clear so I didn't change anything
      properties:
        from:
          type: string
        to:
          type: string
        data:
          type: string
        value:
          type: string
        gasPrice: 
          type: string
        gas:
          type: string
      required:
        - from
        - to
        - data
        - value
        - gasPrice
        - gas
    
    SwapData:
      type: object
      properties:
        fromToken:
          $ref: '#/components/schemas/Token'
        toToken:
          $ref: '#/components/schemas/Token'
        hops:
          type: array
          items:
            $ref: '#/components/schemas/Hop'
      required:
        - fromToken
        - toToken
        - hops